name: Custom Reexecution Benchmark

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write      # Needed to push to gh-pages

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.9'  
      
      - name: Run benchmarks
        run: go run . --benchmark-output-file=benchmark_output.json

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1.20.7
        with:
          tool: 'customBiggerIsBetter'
          output-file-path: benchmark_output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Only update on main branch
          comment-on-alert: false
          fail-on-alert: false